name: Build Projects

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-cmake-x86_64:
    name: Build CMake (x86_64)
    runs-on: windows-latest

    steps:
      - name: Setup NASM
        uses: ilammy/setup-nasm@v1

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure CMake
        run: cmake -S src/x86_64 -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build CMake Project
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

  build-rust-arm64:
    name: Build Rust (ARM64)
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build Rust Project
        run: |
          cd src/arm64
          cargo build --release